// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/afs/cern.ch/user/k/kyee/UG-Analysis/PulseShapes/./Oct_generating_template.cpp";

#endif
