/********************************************************************
* /afs/cern.ch/user/k/kyee/UG-Analysis/PulseShapes/Oct_generating_template_cpp_ACLiC_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /afs/cern.ch/user/k/kyee/UG-Analysis/PulseShapes/Oct_generating_template_cpp_ACLiC_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableOct_generating_template_cpp_ACLiC_dict();
extern void G__cpp_setup_inheritanceOct_generating_template_cpp_ACLiC_dict();
extern void G__cpp_setup_typetableOct_generating_template_cpp_ACLiC_dict();
extern void G__cpp_setup_memvarOct_generating_template_cpp_ACLiC_dict();
extern void G__cpp_setup_globalOct_generating_template_cpp_ACLiC_dict();
extern void G__cpp_setup_memfuncOct_generating_template_cpp_ACLiC_dict();
extern void G__cpp_setup_funcOct_generating_template_cpp_ACLiC_dict();
extern void G__set_cpp_environmentOct_generating_template_cpp_ACLiC_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/afs/cern.ch/user/k/kyee/UG-Analysis/PulseShapes/./Oct_generating_template.cpp"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Oct_generating_template_cpp_ACLiC_dictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__Oct_generating_template_cpp_ACLiC_dictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__Oct_generating_template_cpp_ACLiC_dictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__Oct_generating_template_cpp_ACLiC_dictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__Oct_generating_template_cpp_ACLiC_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Oct_generating_template_cpp_ACLiC_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Oct_generating_template_cpp_ACLiC_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__Oct_generating_template_cpp_ACLiC_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Oct_generating_template_cpp_ACLiC_dictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__Oct_generating_template_cpp_ACLiC_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__Oct_generating_template_cpp_ACLiC_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Oct_generating_template_cpp_ACLiC_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__Oct_generating_template_cpp_ACLiC_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;

/* STUB derived class for protected member access */
